config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  
  get 'prices/index'
  resources :networks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'wallets#index'

  resources :wallets, only: %i[index show destroy] do
    delete :bulk_delete, on: :collection
    get :ontology, on: :collection, to: 'wallets#ontologies'
    get :ontology, on: :member
  end
  resources :trashes
  resources :histories, only: %i[index show]
  resources :prices, only: %i[index]
  resources :tokens, only: %i[] do
    member do
      delete :trash
    end
  end

  get 'import', to: 'import#show'
  post 'import', to: 'import#create'
  get 'refresh', to: 'refreshes#index'
  get 'refresh_ontology', to: 'refreshes#ontology'
  get 'winners', to: 'winners#show'
  post 'winners', to: 'winners#create'
end

app/models/network.rb
# frozen_string_literal: true

class Network < ApplicationRecord
  BSC_CHAIN_ID = 56

  has_many :tokens, dependent: :destroy
  belongs_to :user

  before_save :disallow_inactive_bsc

  scope :actived, -> { where(active: true) }
  scope :have_chain, -> { where.not(chain_id: -1) }

  def self.binance_smart_chain(user)
    find_or_create_by(network_name: 'Binance Smart Chain', chain_id: BSC_CHAIN_ID, user: user)
  end

  def self.ontology(user)
    find_or_create_by(network_name: 'Ontology', chain_id: -1, user: user, scan_url: 'https://explorer.ont.io/address')
  end

  def bsc?
    chain_id == BSC_CHAIN_ID
  end

  def ontology?
    network_name == 'Ontology'
  end

  private

  def disallow_inactive_bsc
    return unless chain_id_was == BSC_CHAIN_ID

    self.chain_id = BSC_CHAIN_ID
    self.network_name = 'Binance Smart Chain'
    self.active = true
  end
end

app/controllers/networks_controller.rb
# frozen_string_literal: true

class NetworksController < ApplicationController
  before_action :set_network, only: %i[edit update destroy]

  # GET /networks or /networks.json
  def index
    @networks = Network.where(user: current_user).have_chain
  end

  # GET /networks/new
  def new
    @network = Network.new
  end

  # GET /networks/1/edit
  def edit; end

  # POST /networks or /networks.json
  def create
    @network = Network.new(network_params.merge(user: current_user))

    respond_to do |format|
      if @network.save
        format.html { redirect_to networks_url, notice: 'Network was successfully created.' }
        format.json { render :show, status: :created, location: @network }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /networks/1 or /networks/1.json
  def update
    respond_to do |format|
      if @network.update(network_params)
        format.html { redirect_to networks_url, notice: 'Network was successfully updated.' }
        format.json { render :show, status: :ok, location: @network }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1 or /networks/1.json
  def destroy
    @network.destroy if @network.chain_id != Network::BSC_CHAIN_ID

    respond_to do |format|
      format.html { redirect_to networks_url, notice: 'Network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_network
    @network = Network.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def network_params
    params.require(:network).permit(:network_name, :chain_id, :scan_url, :active)
  end
end

app/helpers/networks_helper.rb
# frozen_string_literal: true

module NetworksHelper
end

app/views/networks/_form.html.haml
= form_for @network do |f|
  - if @network.errors.any?
    #error_explanation
      %h2= "#{pluralize(@network.errors.count, "error")} prohibited this network from being saved:"
      %ul
        - @network.errors.full_messages.each do |message|
          %li= message
  %table.table.mt-3
    %tr
      %td= f.label :network_name
      %td= f.text_field :network_name, class: 'form-control'
    %tr
      %td= f.label :chain_id
      %td= f.number_field :chain_id, class: 'form-control'
    %tr
      %td= f.label :scan_url
      %td= f.text_area :scan_url, rows: 5, class: 'form-control'
    %tr
      %td= f.label :active
      %td= f.check_box :active, {}, 'true', 'false'
  .actions.mt-2.mb-2
    = f.submit 'Save'

app/views/networks/edit.html.haml
%h1 Editing network

= render 'form'

= link_to 'Show', @network
\|
= link_to 'Back', networks_path

app/views/networks/index.html.haml
%h1 Listing networks

%table.table.table-stripped
  %thead
    %tr
      %th Network name
      %th Chain
      %th Active
      %th
      %th
      %th

  %tbody
    - @networks.each do |network|
      %tr
        %td= network.network_name
        %td= network.chain_id
        %td
          - if network.active
            %i.fa.fa-circle.text-success
          - else
            %i.fa.fa-circle.text-danger
        %td= link_to 'Edit', edit_network_path(network)
        %td= link_to 'Destroy', network, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Network', new_network_path

app/views/networks/new.html.haml
%h1 New network

= render 'form'

= link_to 'Back', networks_path