config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  
  get 'prices/index'
  resources :networks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'wallets#index'

  resources :wallets, only: %i[index show destroy] do
    delete :bulk_delete, on: :collection
    get :ontology, on: :collection, to: 'wallets#ontologies'
    get :ontology, on: :member
  end
  resources :trashes
  resources :histories, only: %i[index show]
  resources :prices, only: %i[index]
  resources :tokens, only: %i[] do
    member do
      delete :trash
    end
  end

  get 'import', to: 'import#show'
  post 'import', to: 'import#create'
  get 'refresh', to: 'refreshes#index'
  get 'refresh_ontology', to: 'refreshes#ontology'
  get 'winners', to: 'winners#show'
  post 'winners', to: 'winners#create'
end

app/models/history.rb
# frozen_string_literal: true

class History < ApplicationRecord
  belongs_to :user
end

app/controllers/histories_controller.rb
# frozen_string_literal: true

class HistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @histories = History.where(user: current_user).order(created_at: :desc)
  end

  def show
    @history = History.find(params[:id])
  end
end

app/views/histories/index.html.haml
%h2 Histories

.row.mb-3.mt-3
  .col-12
    = link_to 'Check winners', winners_path, class: 'btn btn-primary'

%table.table.table-stripped
  %thead
    %tr
      %th #
      %th Wallets

  %tbody
    - @histories.each.with_index(1) do |history, index|
      %tr
        %td
          = link_to index.to_s, history_path(history)
        %td
          - winners = Wallet.where(user: current_user, id: history.wallets)
          - if winners.present?
            - Wallet.where(user: current_user, id: history.wallets).each do |wallet|
              = link_to wallet.address, wallet_path(wallet)
              %br
          - else
            %strong.text-danger
              Cười 1 cái =))
%br

app/views/histories/show.html.haml
.row.mb-3
  .col-12
    = link_to 'Check winners', winners_path, class: 'btn btn-primary'
    = link_to 'Back to Listing', histories_path, class: 'btn btn-primary'
    = link_to 'Wallets', wallets_path, class: 'btn btn-primary'
.row
  .col-12
    %ol{start: '1'}
      - Wallet.where(user: current_user, id: @history.wallets).each do |wallet|
        %li
          = link_to wallet.address, wallet_path(wallet), style: 'word-break: break-word;'