config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  
  get 'prices/index'
  resources :networks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'wallets#index'

  resources :wallets, only: %i[index show destroy] do
    delete :bulk_delete, on: :collection
    get :ontology, on: :collection, to: 'wallets#ontologies'
    get :ontology, on: :member
  end
  resources :trashes
  resources :histories, only: %i[index show]
  resources :prices, only: %i[index]
  resources :tokens, only: %i[] do
    member do
      delete :trash
    end
  end

  get 'import', to: 'import#show'
  post 'import', to: 'import#create'
  get 'refresh', to: 'refreshes#index'
  get 'refresh_ontology', to: 'refreshes#ontology'
  get 'winners', to: 'winners#show'
  post 'winners', to: 'winners#create'
end

app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  has_many :tokens, dependent: :destroy
  belongs_to :user

  enum address_type: {
    bep20: 'BEP20',
    ontology: 'Ontology'
  }

  validates :address, uniqueness: { scope: :user_id, case_sensitive: false, message: 'should be inserted once!' }

  def balance
    tokens.sum(:balance)
  end

  def write_token_number_cache(network)
    tokens.where(network: network).each do |token|
      Rails.cache.fetch(token.token_number_cache_key) { token.number_of_tokens }
    end
  end
end

app/controllers/wallets_controller.rb
# frozen_string_literal: true

class WalletsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_network, only: %i[show]

  def index
    chain_id = params[:chain_id].presence || Network::BSC_CHAIN_ID
    @wallets = bep20_wallets
    if params[:token]
      @wallets =
        @wallets.left_joins(tokens: :network)
                .where(networks: { chain_id: chain_id }, tokens: { contract_ticker_symbol: params[:token] })
    end
    if params[:not_show_small_token] == 'true'
      @wallets =
        @wallets.left_joins(tokens: :network)
                .where('networks.chain_id = ? AND tokens.balance > ?', chain_id, params[:amount])
    end
    @total_balance =
      Token.left_joins(:wallet, :network)
           .where(wallets: @wallets, networks: { chain_id: chain_id })
           .sum(:balance)
           .ceil(2)
  end

  def show
    @wallet = Wallet.find(params[:id])
    @tokens = @wallet.tokens.where(network: @network)
  end

  def ontologies
    @wallets = ontology_wallets
    @total_ong = Token.where(wallet: @wallets, contract_name: 'ONG').sum(:balance).ceil(2)
    @total_ont = Token.where(wallet: @wallets, contract_name: 'ONT').sum(:balance).ceil(2)
  end

  def ontology
    @wallet = Wallet.find(params[:id])
  end

  def destroy
    Wallet.find(params[:id]).destroy
    redirect_to wallets_path
  end

  def bulk_delete
    Wallet.where(user: current_user).bep20.destroy_all
    redirect_to wallets_path
  end

  private

  def set_network
    @network = Network.find_by(chain_id: params[:chain_id],
                               user: current_user) || Network.binance_smart_chain(current_user)
  end

  def bep20_wallets
    @bep20_wallets ||= Wallet.distinct.bep20.where(user: current_user).order(:id)
  end

  def ontology_wallets
    @ontology_wallets ||= Wallet.includes(:tokens).ontology.where(user: current_user).order(:id)
  end
end

app/helpers/wallets_helper.rb
# frozen_string_literal: true

module WalletsHelper
  def network_options
    Network.have_chain
           .actived
           .where(user: current_user)
           .pluck(:network_name, :chain_id)
  end

  def current_chain
    params[:chain_id].presence || Network::BSC_CHAIN_ID
  end

  def wallet_balance(wallet)
    Token
      .left_joins(:network)
      .where(wallets: wallet, networks: { chain_id: current_chain })
      .sum(&:balance)
      .ceil(2)
  end

  def token_options
    Token.distinct
         .select(:contract_name, :contract_ticker_symbol)
         .where.not(contract_address: Token::ONTOLOGY_CONTRACT_ADDRESS)
         .order(:contract_ticker_symbol).pluck(:contract_ticker_symbol)
  end
end

app/views/wallets/index.html.haml
.row.mb-1
  .col-md-12.col-sm-12.mb-2
    %button.btn.btn-primary.mb-2#refresh
      Refresh
    %a{href: prices_path, class: 'btn btn-primary mb-2'}
      Prices
    = render '/pages'
.row
  .col-6
    %a.btn.btn-success.mb-3{href: ontology_wallets_path}
      Ontology
  .col-6
    %strong.mt-2{style: 'float: right;'}
      Balance:
      = @total_balance.to_s + ' USD'
.row
  .col-md-3.col-sm-12
    = select_tag 'network', options_for_select(network_options, current_chain), class: 'form-control mb-3'
  .col-md-3.col-sm-12
    = select_tag 'token-search', options_for_select(token_options, params[:token]), include_blank: true, class: 'form-control select2'
.row.mb-3
  .col-md-6.col-sm-12.mt-2
    .row
      .col-12
        = number_field_tag 'small_token_amount', params[:amount].to_f || 0.0, min: 0.0, step: 0.1, class: 'form-control'
    .row
      .col-12
        .form-check
          = check_box_tag :not_show_small_token, 'true', params[:not_show_small_token] == 'true', class: 'form-check-input'
          %label.form-check-label{for: 'not_show_small_token'} 
            Do not show
            %strong SMALL
            account
  .col-md-6.col-sm-12.d-flex.justify-content-end
    = link_to 'Delete All', bulk_delete_wallets_path, method: :delete, class: 'btn btn-danger float-right', style: 'height: 40px;', data: { confirm: 'Are you sure?' }
.row
  .col-12
    %table.table.table-stripped
      %thead
        %tr
          %th #
          %th Address
          %th Balance
          %th Copy
          %th{style: 'width: 50px'} Actions
      %tbody
        - @wallets.each.with_index(1) do |wallet, index|
          %tr
            %td
              = index
            %td
              - if wallet.address.present?
                = link_to wallet.address[0..5] + '*****' + wallet.address[-5..-1], wallet_path(wallet)
            %td
              = wallet_balance(wallet).to_s + ' USD'
            %td
              %a.copy-clipboard{href: '#', data: { address: wallet.address }}
                %i.fa.fa-clipboard
            %td
              = link_to 'Delete', wallet_path(wallet), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }
        %tr
          %td
          %td
          %td
            %strong
              = @total_balance.to_s + ' USD'

:javascript
  if (localStorage.getItem('smallTokenNumber')) {
    $('#small_token_amount').val(localStorage.getItem('smallTokenNumber'))
  }

  $('#network').on('change', function() {
    let queryParams = new URLSearchParams(window.location.search)
    queryParams.set('chain_id', $(this).val())
    window.location.href = window.location.origin + window.location.pathname + '?' + queryParams.toString()
  })

  $('#token-search').on('change', function() {
    let queryParams = new URLSearchParams(window.location.search)
    if ($(this).val()) {
      queryParams.set('token', $(this).val())
    } else {
      queryParams.delete('token')
    }
    window.location.href = window.location.origin + window.location.pathname + '?' + queryParams.toString()
  })

  $('#not_show_small_token').on('change', function() {
    let queryParams = new URLSearchParams(window.location.search)
    let url = window.location.origin + window.location.pathname

    if ($(this).is(':checked')) {
      queryParams.set('not_show_small_token', true)
      queryParams.set('amount', $('#small_token_amount').val())
      url = url + '?' + queryParams.toString()
    } else {
      queryParams.set('not_show_small_token', false)
      queryParams.delete('amount')
      url = url + '?' + queryParams.toString()
    }
    window.location.href = url
  })

  $('#small_token_amount').on('change', function() {
    let queryParams = new URLSearchParams(window.location.search)
    let url = window.location.origin + window.location.pathname

    if ($('#not_show_small_token').is(':checked')) {
      queryParams.set('not_show_small_token', true)
      queryParams.set('amount', $(this).val())
      url = url + '?' + queryParams.toString()

      localStorage.setItem('smallTokenNumber', $(this).val());
    }
    window.location.href = url
  })

  $('#refresh').on('click', function() {
    $.ajax({
      url: '/refresh?chain_id=' + $('#network').val(),
      type: 'GET',
      async: true
    })
    alert('Refreshing')
  })

  $('.copy-clipboard').on('click', function(e) {
    e.preventDefault()
    navigator.clipboard.writeText($(this).data('address'))
  })

app/views/wallets/ontologies.html.haml
.row.mb-1
  .col-md-12.col-sm-12.mb-2
    %button.btn.btn-primary.mb-2#refresh
      Refresh
    %a{href: prices_path, class: 'btn btn-primary mb-2'}
      Prices
    = render '/pages'
.row
  .col-12
    %a.btn.btn-success.mb-3{href: wallets_path}
      BEP20
.row
  .col-12
    %strong
      ONG:
      = @total_ong
    |
    %strong
      ONT:
      = @total_ont
.row
  .col-12
    %table.table.table-stripped
      %thead
        %tr
          %th #
          %th Address
          %th Balance
          %th Copy
          %th{style: 'width: 50px'} Actions
      %tbody
        - @wallets.each.with_index(1) do |wallet, index|
          %tr
            %td
              = index
            %td
              - if wallet.address.present?
                = link_to wallet.address[0..5] + '*****' + wallet.address[-5..-1], ontology_wallet_path(wallet)
            %td
              - tokens = wallet.tokens.where(contract_name: %w[ONG ONT])
              - tokens.each.with_index(1) do |token, index|
                %span
                  = token.balance
                  = token.contract_name
                - if index != tokens.count
                  |
            %td
              %a.copy-clipboard{href: '#', data: { address: wallet.address }}
                %i.fa.fa-clipboard
            %td
              = link_to 'Delete', wallet_path(wallet), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }

:javascript
  $('#refresh').on('click', function() {
    $.ajax({
      url: '/refresh_ontology',
      type: 'GET',
      async: true
    })
    alert('Refreshing')
  })

  $('.copy-clipboard').on('click', function(e) {
    e.preventDefault()
    navigator.clipboard.writeText($(this).data('address'))
  })

app/views/wallets/ontology.html.haml
%h2.mb-4{style: 'word-break: break-word;'}
  = @wallet.address
.row.mb-2
  .col-md-3.col-sm-12
    %button.btn.btn-primary#refresh
      Refresh
    %a{href: ontology_wallets_path, class: 'btn btn-primary'}
      Wallets
- @wallet.tokens.each do |token|
  .card.mb-2
    .row.no-gutters
      .col-12
        .card-body
          %h5.card-title
            = token.contract_ticker_symbol
          %p.card-text
            %strong
              Contract Address:
            = token.contract_address
            %br
            %strong
              Balance:
            = token.balance.ceil(2)
          - if token.network.scan_url.present?
            %a.btn.btn-primary{:href => "#{token.network.scan_url}/#{@wallet.address}", target: '_blank'}
              View on
              = token.network.network_name
              scan
          - else
            %a.btn.btn-secondary.disabled{:href => "#", style: 'opacity: 0.4;'} 
              View on
              = token.network.network_name
              scan

:javascript
  $('#refresh').on('click', function() {
    $.ajax({
      url: '/refresh_ontology?wallet_id=' + "#{params[:id]}",
      type: 'GET',
      success: function () {
        location.reload()
      },
      async: false
    })
  })

app/views/wallets/show.html.haml
%h2.mb-4{style: 'word-break: break-word;'}
  = @wallet.address
.row.mb-2
  .col-md-3.col-sm-12
    = select_tag 'network', options_for_select(Network.actived.where(user: current_user).pluck(:network_name, :chain_id), params[:chain_id].presence || Network::BSC_CHAIN_ID), class: 'form-control mb-3'
  .col-md-3.col-sm-12
    %button.btn.btn-primary#refresh
      Refresh
    %a{href: wallets_path, class: 'btn btn-primary'}
      Wallets
- @tokens.each do |token|
  .card.mb-2
    .row.no-gutters
      .col-md-2.col-sm-12.text-center
        %img.card-img{:alt => token.contract_name, src: token.logo_url, onerror: "this.onerror=null;this.src='/404.png';", style: 'padding: 20px; height: 200px; width: 200px;'}/
      .col-md-8.col-sm-12
        .card-body
          %h5.card-title
            = token.contract_ticker_symbol
          %p.card-text
            %strong
              Contract Name:
            = token.contract_name
            %br
            %strong
              Contract Address:
            = token.contract_address
            %br
            %strong
              Balance:
            = token.balance.ceil(2).to_s + ' USD'
            %br
            %strong
              Price:
            = token.quote_rate.to_f.ceil(10).to_s
          - if token.network.scan_url.present?
            %a.btn.btn-primary{:href => "#{token.network.scan_url}/#{@wallet.address}", target: '_blank'}
              View on
              = token.network.network_name
              scan
          - else
            %a.btn.btn-secondary.disabled{:href => "#", style: 'opacity: 0.4;'} 
              View on
              = token.network.network_name
              scan
    %a.trash{href: '#', data: { id: token.id, contract_name: token.contract_name }}
      Trash

:javascript
  $('#network').on('change', function() {
    let queryParams = new URLSearchParams(window.location.search)
    queryParams.set('chain_id', $(this).val())
    history.replaceState(null, null, "?"+queryParams.toString())
    window.location.href = window.location.origin + window.location.pathname + '?' + queryParams.toString()
  })

  $('#refresh').on('click', function() {
    $.ajax({
      url: '/refresh?wallet_id=' + "#{params[:id]}" + '&chain_id=' + "#{params[:chain_id]}",
      type: 'GET',
      success: function () {
        location.reload()
      },
      async: false
    })
  })

  $('a.trash').on('click', function() {
    $.ajax({
      url: '/tokens/' + $(this).data('id') + '/trash?contract_name=' + $(this).data('contractName'),
      type: 'DELETE',
      success: function () {
        location.reload()
      }
    })
  })