config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  
  get 'prices/index'
  resources :networks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'wallets#index'

  resources :wallets, only: %i[index show destroy] do
    delete :bulk_delete, on: :collection
    get :ontology, on: :collection, to: 'wallets#ontologies'
    get :ontology, on: :member
  end
  resources :trashes
  resources :histories, only: %i[index show]
  resources :prices, only: %i[index]
  resources :tokens, only: %i[] do
    member do
      delete :trash
    end
  end

  get 'import', to: 'import#show'
  post 'import', to: 'import#create'
  get 'refresh', to: 'refreshes#index'
  get 'refresh_ontology', to: 'refreshes#ontology'
  get 'winners', to: 'winners#show'
  post 'winners', to: 'winners#create'
end

app/models/trash.rb
# frozen_string_literal: true

class Trash < ApplicationRecord
  after_create :remove_trash_tokens

  private

  def remove_trash_tokens
    Token.where(contract_name: contract_name).destroy_all
  end
end

app/controllers/trashes_controller.rb
# frozen_string_literal: true

class TrashesController < ApplicationController
  before_action :set_trash, only: %i[edit update destroy]

  # GET /trashes or /trashes.json
  def index
    @trashes = Trash.all
  end

  # GET /trashes/new
  def new
    @trash = Trash.new
  end

  # GET /trashes/1/edit
  def edit; end

  # POST /trashes or /trashes.json
  def create
    @trash = Trash.new(trash_params)

    respond_to do |format|
      if @trash.save
        format.html { redirect_to trashes_url, notice: 'Trash was successfully created.' }
        format.json { render :show, status: :created, location: @trash }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trashes/1 or /trashes/1.json
  def update
    respond_to do |format|
      if @trash.update(trash_params)
        format.html { redirect_to trashes_url, notice: 'Trash was successfully updated.' }
        format.json { render :show, status: :ok, location: @trash }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trashes/1 or /trashes/1.json
  def destroy
    @trash.destroy

    respond_to do |format|
      format.html { redirect_to trashes_url, notice: 'Trash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trash
    @trash = Trash.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def trash_params
    params.require(:trash).permit(:contract_name)
  end
end

app/helpers/trashes_helper.rb
# frozen_string_literal: true

module TrashesHelper
end

app/views/trashes/_form.html.haml
= form_for @trash do |f|
  - if @trash.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trash.errors.count, "error")} prohibited this trash from being saved:"
      %ul
        - @trash.errors.full_messages.each do |message|
          %li= message
  %table.table.mt-3
    %tr
      %td Contract Name
      %td
        = f.text_field :contract_name, class: 'form-control'
  .actions.mt-2.mb-2
    = f.submit 'Save'

app/views/trashes/edit.html.haml
%h1 Editing trash

= render 'form'

= link_to 'Show', @trash
\|
= link_to 'Back', trashes_path

app/views/trashes/index.html.haml
%h1 Listing trashes

.row
  .col-12
    = link_to 'New Trash', new_trash_path

%table.table.table-stripped
  %thead
    %tr
      %th #
      %th Contract Name
      %th
      %th

  %tbody
    - @trashes.each.with_index(1) do |trash, index|
      %tr
        %td= index
        %td= trash.contract_name
        %td= link_to 'Edit', edit_trash_path(trash)
        %td= link_to 'Destroy', trash, method: :delete, data: { confirm: 'Are you sure?' }

app/views/trashes/new.html.haml
%h1 New trash

= render 'form'

= link_to 'Back', trashes_path